import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

import { Bricolage_Grotesque } from "next/font/google";
import { Lexend } from "next/font/google";
import { Header } from "./_components/Header/Header";

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-lexend",
  display: "swap",
});
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  display: "swap",
});
export const metadata: Metadata = {
  title: "PropZoid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={cn("h-full", "antialiased", "font-sans")}>
        <body
          className={`${lexend.variable} ${bricolage.className} min-h-screen flex flex-col  `}
        >
          <Toaster position="top-right" richColors />
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
